### ISSUE TITLE
Access selectors from action creators

### ISSUE THREAD

**Issue by nratter** [investtools/extensible-duck#11]
Hey fellas... really loving this tool!

Is there any way to access selectors inside action creators?

**Comment by akelmanson** [comment]
Hi @nratter. Glad to know you are enjoying this lib!

I'm on vacation without my computer. @aga5tya, could you please help @nratter?

**Comment by aga5tya** [comment]
@nratter since creators function call is invoked before selectors, they won't have access to it, swapping this [line](https://github.com/investtools/extensible-duck/blob/42ebc2b62941414d3ea78ca0ae1c74a899957562/src/extensible-duck.js#L132) with the next line should give you selectors access.

Just curious, is there a specific case you'd want to use selectors in action creator's ? thunks maybe ?

**Comment by nratter** [comment]
@aga5tya not a specific case. But, in order to use selectors in action creators with this lib, they have to be passed in as parameters. It may be nice to be able to access the selectors directly.

**Comment by akelmanson** [comment]
@nratter You can use v1.2.1.

Example here: https://github.com/investtools/extensible-duck/blob/master/test/unit/extensible-duck.js#L70

**Comment by nratter** [comment]
@akelmanson awesome! thanks!
